<?php
// $Id: page_manager_blank.module,v 1.3.2.2.2.2 2011/01/10 17:19:27 jameswilliams Exp $

/**
 * Implements hook_ctools_plugin_directory() to let the system know
 * we implement page manager task handlers.
 */
function page_manager_blank_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Page manager redirect path helper function.
 */
function page_manager_blank_get_path($file, $base_path = FALSE, $module = 'page_manager_blank') {
  $output = $base_path ? base_path() : '';
  return $output . drupal_get_path('module', $module) . '/' . $file;
}
